@startuml

skinparam SequenceMessageAlign center

activate RegisterDFSTest
' RegisterDFSTest
RegisterDFSTest --> DocumentSafeService : registerDFSCredentials

activate DocumentSafeService
' DocumentSafeService
DocumentSafeService --> DocumentSafeServiceImpl : registerDFSCredentials

activate DocumentSafeServiceImpl
' DocumentSafeServiceImpl
DocumentSafeServiceImpl --> DocumentSafeServiceImpl : getUsersAccess

activate DocumentSafeServiceImpl
' DocumentSafeServiceImpl
DocumentSafeServiceImpl --> DocumentSafeServiceImpl : getUsersAccess

activate DocumentSafeServiceImpl
' DocumentSafeServiceImpl
DocumentSafeServiceImpl --> DocumentSafeServiceImpl : getUsersDFS

activate DocumentSafeServiceImpl
' DocumentSafeServiceImpl
DocumentSafeServiceImpl --> DocumentSafeServiceImpl : getKeyStoreAccess

activate DocumentSafeServiceImpl
' DocumentSafeServiceImpl
DocumentSafeServiceImpl --> FolderHelper : getKeyStorePath

activate FolderHelper
' FolderHelper
DocumentSafeServiceImpl <-- FolderHelper : BucketPath
deactivate FolderHelper

' DocumentSafeServiceImpl
DocumentSafeServiceImpl --> DFSConnection : getBlob

activate DFSConnection
' de.adorsys.dfs.connection.api.service.api.DFSConnection
DocumentSafeServiceImpl <-- DFSConnection : Payload
deactivate DFSConnection

' DocumentSafeServiceImpl
DocumentSafeServiceImpl <-- DocumentSafeServiceImpl : KeyStoreAccess
deactivate DocumentSafeServiceImpl

' DocumentSafeServiceImpl
DocumentSafeServiceImpl --> FolderHelper : getDFSCredentialsPath

activate FolderHelper
' FolderHelper
DocumentSafeServiceImpl <-- FolderHelper : BucketPath
deactivate FolderHelper

' DocumentSafeServiceImpl
DocumentSafeServiceImpl --> DFSConnection : getBlob

activate DFSConnection
' de.adorsys.dfs.connection.api.service.api.DFSConnection
DocumentSafeServiceImpl <-- DFSConnection : Payload
deactivate DFSConnection

' DocumentSafeServiceImpl
DocumentSafeServiceImpl --> CMSEncryptionService : decrypt

activate CMSEncryptionService
' CMSEncryptionService
CMSEncryptionService --> CMSEncryptionServiceImpl : decrypt

activate CMSEncryptionServiceImpl
' CMSEncryptionServiceImpl
CMSEncryptionService <-- CMSEncryptionServiceImpl : Payload
deactivate CMSEncryptionServiceImpl

' CMSEncryptionService
DocumentSafeServiceImpl <-- CMSEncryptionService : Payload
deactivate CMSEncryptionService

' DocumentSafeServiceImpl
DocumentSafeServiceImpl --> Class2JsonHelper : contentToDFSConnection

activate Class2JsonHelper
' Class2JsonHelper
DocumentSafeServiceImpl <-- Class2JsonHelper : DFSCredentials
deactivate Class2JsonHelper

' DocumentSafeServiceImpl
DocumentSafeServiceImpl --> DFSConnectionFactory : get

activate DFSConnectionFactory
' de.adorsys.dfs.connection.impl.factory.DFSConnectionFactory
DocumentSafeServiceImpl <-- DFSConnectionFactory : DFSConnection
deactivate DFSConnectionFactory

' DocumentSafeServiceImpl
DocumentSafeServiceImpl <-- DocumentSafeServiceImpl : DFSConnection
deactivate DocumentSafeServiceImpl

' DocumentSafeServiceImpl
DocumentSafeServiceImpl --> DocumentSafeServiceImpl : getKeyStoreAccess

activate DocumentSafeServiceImpl
' DocumentSafeServiceImpl
DocumentSafeServiceImpl --> FolderHelper : getKeyStorePath

activate FolderHelper
' FolderHelper
DocumentSafeServiceImpl <-- FolderHelper : BucketPath
deactivate FolderHelper

' DocumentSafeServiceImpl
DocumentSafeServiceImpl --> DFSConnection : getBlob

activate DFSConnection
' de.adorsys.dfs.connection.api.service.api.DFSConnection
DocumentSafeServiceImpl <-- DFSConnection : Payload
deactivate DFSConnection

' DocumentSafeServiceImpl
DocumentSafeServiceImpl <-- DocumentSafeServiceImpl : KeyStoreAccess
deactivate DocumentSafeServiceImpl

' DocumentSafeServiceImpl
DocumentSafeServiceImpl --> KeyStoreService : getRandomSecretKeyID

activate KeyStoreService
' KeyStoreService
KeyStoreService --> KeyStoreServiceImpl : getRandomSecretKeyID

activate KeyStoreServiceImpl
' KeyStoreServiceImpl
KeyStoreService <-- KeyStoreServiceImpl : SecretKeyIDWithKey
deactivate KeyStoreServiceImpl

' KeyStoreService
DocumentSafeServiceImpl <-- KeyStoreService : SecretKeyIDWithKey
deactivate KeyStoreService

' DocumentSafeServiceImpl
DocumentSafeServiceImpl --> DocumentSafeServiceImpl : getKeyStoreAccess

activate DocumentSafeServiceImpl
' DocumentSafeServiceImpl
DocumentSafeServiceImpl --> FolderHelper : getKeyStorePath

activate FolderHelper
' FolderHelper
DocumentSafeServiceImpl <-- FolderHelper : BucketPath
deactivate FolderHelper

' DocumentSafeServiceImpl
DocumentSafeServiceImpl --> DFSConnection : getBlob

activate DFSConnection
' de.adorsys.dfs.connection.api.service.api.DFSConnection
DocumentSafeServiceImpl <-- DFSConnection : Payload
deactivate DFSConnection

' DocumentSafeServiceImpl
DocumentSafeServiceImpl <-- DocumentSafeServiceImpl : KeyStoreAccess
deactivate DocumentSafeServiceImpl

' DocumentSafeServiceImpl
DocumentSafeServiceImpl --> FolderHelper : getHomeDirectory

activate FolderHelper
' FolderHelper
FolderHelper --> BucketDirectory : appendDirectory

activate BucketDirectory
' de.adorsys.dfs.connection.api.complextypes.BucketDirectory
FolderHelper <-- BucketDirectory : BucketDirectory
deactivate BucketDirectory

' FolderHelper
DocumentSafeServiceImpl <-- FolderHelper : BucketDirectory
deactivate FolderHelper

' DocumentSafeServiceImpl
DocumentSafeServiceImpl --> BucketPathEncryptionService : encrypt

activate BucketPathEncryptionService
' BucketPathEncryptionService
BucketPathEncryptionService --> BucketPathEncryptionServiceImpl : encrypt

activate BucketPathEncryptionServiceImpl
' BucketPathEncryptionServiceImpl
BucketPathEncryptionService <-- BucketPathEncryptionServiceImpl : BucketPath
deactivate BucketPathEncryptionServiceImpl

' BucketPathEncryptionService
DocumentSafeServiceImpl <-- BucketPathEncryptionService : BucketPath
deactivate BucketPathEncryptionService

' DocumentSafeServiceImpl
DocumentSafeServiceImpl --> FolderHelper : getHomeDirectory

activate FolderHelper
' FolderHelper
FolderHelper --> BucketDirectory : appendDirectory

activate BucketDirectory
' de.adorsys.dfs.connection.api.complextypes.BucketDirectory
FolderHelper <-- BucketDirectory : BucketDirectory
deactivate BucketDirectory

' FolderHelper
DocumentSafeServiceImpl <-- FolderHelper : BucketDirectory
deactivate FolderHelper

' DocumentSafeServiceImpl
DocumentSafeServiceImpl --> BucketDirectory : appendDirectory

activate BucketDirectory
' de.adorsys.dfs.connection.api.complextypes.BucketDirectory
DocumentSafeServiceImpl <-- BucketDirectory : BucketDirectory
deactivate BucketDirectory

' DocumentSafeServiceImpl
DocumentSafeServiceImpl --> BucketPathEncryptionService : encrypt

activate BucketPathEncryptionService
' BucketPathEncryptionService
BucketPathEncryptionService --> BucketPathEncryptionServiceImpl : encrypt

activate BucketPathEncryptionServiceImpl
' BucketPathEncryptionServiceImpl
BucketPathEncryptionService <-- BucketPathEncryptionServiceImpl : BucketDirectory
deactivate BucketPathEncryptionServiceImpl

' BucketPathEncryptionService
DocumentSafeServiceImpl <-- BucketPathEncryptionService : BucketDirectory
deactivate BucketPathEncryptionService

' DocumentSafeServiceImpl
DocumentSafeServiceImpl <-- DocumentSafeServiceImpl : DFSAndKeystoreAndPath
deactivate DocumentSafeServiceImpl

' DocumentSafeServiceImpl
DocumentSafeServiceImpl <-- DocumentSafeServiceImpl : DFSAndKeystoreAndPath
deactivate DocumentSafeServiceImpl

' DocumentSafeServiceImpl
DocumentSafeServiceImpl --> DFSConnectionFactory : get

activate DFSConnectionFactory
' de.adorsys.dfs.connection.impl.factory.DFSConnectionFactory
DocumentSafeServiceImpl <-- DFSConnectionFactory : DFSConnection
deactivate DFSConnectionFactory

' DocumentSafeServiceImpl
DocumentSafeServiceImpl --> DFSConnection : listAllBuckets

activate DFSConnection
' de.adorsys.dfs.connection.api.service.api.DFSConnection
DocumentSafeServiceImpl <-- DFSConnection : List
deactivate DFSConnection

' DocumentSafeServiceImpl
DocumentSafeServiceImpl --> DFSConnection : createContainer

activate DFSConnection
' de.adorsys.dfs.connection.api.service.api.DFSConnection
DocumentSafeServiceImpl <-- DFSConnection :  
deactivate DFSConnection

' DocumentSafeServiceImpl
DocumentSafeServiceImpl --> DFSConnection : list

activate DFSConnection
' de.adorsys.dfs.connection.api.service.api.DFSConnection
DocumentSafeServiceImpl <-- DFSConnection : List
deactivate DFSConnection

' DocumentSafeServiceImpl
DocumentSafeServiceImpl --> DFSConnection : getBlob

activate DFSConnection
' de.adorsys.dfs.connection.api.service.api.DFSConnection
DocumentSafeServiceImpl <-- DFSConnection : Payload
deactivate DFSConnection

' DocumentSafeServiceImpl
DocumentSafeServiceImpl --> DFSConnection : putBlob

activate DFSConnection
' de.adorsys.dfs.connection.api.service.api.DFSConnection
DocumentSafeServiceImpl <-- DFSConnection :  
deactivate DFSConnection

' DocumentSafeServiceImpl
DocumentSafeServiceImpl --> DocumentSafeServiceImpl : getKeyStoreAccess

activate DocumentSafeServiceImpl
' DocumentSafeServiceImpl
DocumentSafeServiceImpl --> FolderHelper : getKeyStorePath

activate FolderHelper
' FolderHelper
DocumentSafeServiceImpl <-- FolderHelper : BucketPath
deactivate FolderHelper

' DocumentSafeServiceImpl
DocumentSafeServiceImpl --> DFSConnection : getBlob

activate DFSConnection
' de.adorsys.dfs.connection.api.service.api.DFSConnection
DocumentSafeServiceImpl <-- DFSConnection : Payload
deactivate DFSConnection

' DocumentSafeServiceImpl
DocumentSafeServiceImpl <-- DocumentSafeServiceImpl : KeyStoreAccess
deactivate DocumentSafeServiceImpl

' DocumentSafeServiceImpl
DocumentSafeServiceImpl --> DocumentSafeServiceImpl : storeUserDFSCredentials

activate DocumentSafeServiceImpl
' DocumentSafeServiceImpl
DocumentSafeServiceImpl --> KeyStoreService : getPublicKeys

activate KeyStoreService
' KeyStoreService
KeyStoreService --> KeyStoreServiceImpl : getPublicKeys

activate KeyStoreServiceImpl
' KeyStoreServiceImpl
KeyStoreService <-- KeyStoreServiceImpl : PublicKeyList
deactivate KeyStoreServiceImpl

' KeyStoreService
DocumentSafeServiceImpl <-- KeyStoreService : PublicKeyList
deactivate KeyStoreService

' DocumentSafeServiceImpl
DocumentSafeServiceImpl --> Class2JsonHelper : dfsCredentialsToContent

activate Class2JsonHelper
' Class2JsonHelper
DocumentSafeServiceImpl <-- Class2JsonHelper : Payload
deactivate Class2JsonHelper

' DocumentSafeServiceImpl
DocumentSafeServiceImpl --> CMSEncryptionService : encrypt

activate CMSEncryptionService
' CMSEncryptionService
CMSEncryptionService --> CMSEncryptionServiceImpl : encrypt

activate CMSEncryptionServiceImpl
' CMSEncryptionServiceImpl
CMSEncryptionService <-- CMSEncryptionServiceImpl : CMSEnvelopedData
deactivate CMSEncryptionServiceImpl

' CMSEncryptionService
DocumentSafeServiceImpl <-- CMSEncryptionService : CMSEnvelopedData
deactivate CMSEncryptionService

' DocumentSafeServiceImpl
DocumentSafeServiceImpl --> FolderHelper : getDFSCredentialsPath

activate FolderHelper
' FolderHelper
DocumentSafeServiceImpl <-- FolderHelper : BucketPath
deactivate FolderHelper

' DocumentSafeServiceImpl
DocumentSafeServiceImpl --> DFSConnection : putBlob

activate DFSConnection
' de.adorsys.dfs.connection.api.service.api.DFSConnection
DocumentSafeServiceImpl <-- DFSConnection :  
deactivate DFSConnection

' DocumentSafeServiceImpl
DocumentSafeServiceImpl <-- DocumentSafeServiceImpl :  
deactivate DocumentSafeServiceImpl

' DocumentSafeServiceImpl
DocumentSafeServiceImpl --> DFSConnection : listAllBuckets

activate DFSConnection
' de.adorsys.dfs.connection.api.service.api.DFSConnection
DocumentSafeServiceImpl <-- DFSConnection : List
deactivate DFSConnection

' DocumentSafeServiceImpl
DocumentSafeServiceImpl --> DFSConnection : deleteContainer

activate DFSConnection
' de.adorsys.dfs.connection.api.service.api.DFSConnection
DocumentSafeServiceImpl <-- DFSConnection :  
deactivate DFSConnection

' DocumentSafeServiceImpl
DocumentSafeService <-- DocumentSafeServiceImpl :  
deactivate DocumentSafeServiceImpl

' DocumentSafeService
RegisterDFSTest <-- DocumentSafeService :  
deactivate DocumentSafeService

@enduml
